default_config:

input_select:
    room_light:
        name : "Vælg etage"
        icon: mdi:home-lightbulb
        options:
        - "Første sal"
        - "Stue"
        - "Kælder"
        - "Udendørs"

# Text to speech
tts:
  - platform: google_translate
    language: 'da'

google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret


sun:

lovelace:
  mode: yaml
  resources: !include_dir_merge_list lovelace/resources/

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include_dir_merge_named lovelace/customizations

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list lovelace/sensors
      
notify:
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_jacob_buch_hansen
      - service: mobile_app_pernille_therkildsens_iphone
      - service: mobile_app_in2023
      
  - name: parents
    platform: group
    services:
      - service: mobile_app_jacob_buch_hansen
      - service: mobile_app_pernille_therkildsens_iphone

discovery:

browser_mod: